#currently in directory where the dataset household_power_consumption.txt is saved

par(mfrow=c(2,2))
data<-read.table("household_power_consumption.txt",sep = ";",header = TRUE,stringsAsFactors = FALSE)
newdata<-data[data$Date %in% c("1/2/2007","2/2/2007"), ]
newdata$Global_active_power<-as.numeric(newdata$Global_active_power)
newdata$Date1<-strptime(paste(newdata$Date,newdata$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
with(newdata,plot(Date1,Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)",xlab = " ",col="black"))
with(newdata,plot(Date1,Voltage,type = "l",col="black",xlab = "datetime"))
newdata$Sub_metering_1<-as.numeric(newdata$Sub_metering_1)
newdata$Sub_metering_2<-as.numeric(newdata$Sub_metering_2)
newdata$Sub_metering_3<-as.numeric(newdata$Sub_metering_3)
with(newdata,plot(Date1,Sub_metering_1,type = "l",col="black",ylab = "Energy Sub Metering",xlab = " "))
with(newdata,points(Date1,Sub_metering_2,type = "l",col="red"))
with(newdata,points(Date1,Sub_metering_3,type = "l",col="blue"))
legend("topright",pch = "-",col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
newdata$Global_reactive_power<-as.numeric(newdata$Global_reactive_power)
with(newdata,plot(Date1,Global_reactive_power,type = "l",col="black",xlab = "datetime",ylab = "Global_reactive_power"))
dev.copy(png,"plot4.png",width=480,height=480)
dev.off()
